### ISSUE TITLE
Weppy docs in PDF format !

### ISSUE THREAD

**Issue by jigarmistry** [emmett-framework/emmett#123]
Is there any possibility to have docs in PDF format?

**Comment by gi0baro** [comment]
Hi @jigarmistry, this shouldn't be hard, but I have to find a way to convert the website rendered ones including links removal and including images.
I will spend some time on this after the next release, if you have any hints I will appreciate :)

**Comment by jigarmistry** [comment]
I don't know about how you build your website pages from .md files? (I didn't find any repo for website). If any then I can find some alternative for the same.

**Comment by gi0baro** [comment]
@jigarmistry the source code of the website is available here: https://github.com/gi0baro/weppy-website

**Comment by Marlysson** [comment]
Could to use the Read Docs to generate documentation and after the pdf version:

http://read-the-docs.readthedocs.io/en/latest/features.html#pdf-generation
