### ISSUE TITLE
Authentication Question ! 

### ISSUE THREAD

**Issue by jigarmistry** [emmett-framework/emmett#127]
In my system I have four types of roles : Teacher,Student,Admin and Parent.
Now I need four different types of registration form as all the roles needs different fields.
How can I manage login and registration for this four types of roles within weppy? 

(I think this is related to Authentication Module).

**Comment by gi0baro** [comment]
Hi @jigarmistry,
to better understand what you need, the main question is: who decide the role of the users? Should be selected by the admin itself, should be performed on the registration in consequence of some conditions?

Also, when you have implementation questions, please consider using the google group: https://groups.google.com/forum/#!forum/weppy-talk

**Comment by jigarmistry** [comment]
Thanks for reply.
Sorry but I don't have access to google groups when I am in working environment.

For your question, I will have three registration form into system and user register into system using form.
When user register into system as teacher then that would be teacher role in system. My question is how we can manage registration form and login for these types of roles? (If teacher logged into system then only teacher access material will be shown to teacher).

There also possible that admin can register teacher/student/parent into system using registration form.

**Comment by gi0baro** [comment]
Ok, sorry for the late response but I was quite over-loaded. This is the best implementation I can think about.

1) I would add the groups for your roles on your application, ideally inside a setup command:

```python
auth.add_group("admin")
auth.add_group("teacher")
auth.add_group("parent")
auth.add_group("student")
db.commit()
```

2) I would create separate routes for signups, so you can bind the role to session depending on the form:

```python
@app.route("/signup/teacher", layout="youraccounttemplate.html")
def signup_teacher():
    session._signup_group = "teacher"
    return {"form": auth("register")}
```

3) I would add an after_insert callback into your user model so that it will add the created user to the relevant group using the session value stored in 2:

```python
class User(AuthUser):
    @after_insert
    def _add_user_to_group(self, fields, uid):
        from myapp import auth
        session._signup_group = session._signup_group or "student"
        group = self.db.AuthGroup(role=session._signup_group)
        auth.add_membership(group, uid)
        del session._signup_group
```

4) Then you can restrict access to sections using the `requires` decorator as usual:

```python
@app.route("/yourteacherroute")
@requires(lambda: auth.has_membership('teacher'), url('index'))
def yourprotectedroute():
    # some awesome code
```

Let me know if this works within your application flow.

**Comment by jigarmistry** [comment]
Thanks for great explanation.
This is what I exactly wanted. But in the 2nd point if I return auth("register") then how can I manage different fields(teacher,student) for registration form ? 

In my case I do have different registration form for all the roles.

**Comment by gi0baro** [comment]
Why do you need additional fields? Customizing the form is a thing, having different fields is a model related thing.

**Comment by jigarmistry** [comment]
So as per my understanding I need to have four different models for four registration form with different fields.(If I am wrong then please tell me).

**Comment by gi0baro** [comment]
@jigarmistry no, it depends what you want to achieve. Also, I think auth module won't work with multiple models for users so I discourage this.
If you just need to customise the template or the form appearance, you can do it with `custom` attribute of forms and html.
I you need to add details about users (for example profiling), my hint is to use a single user model and a separate table with those fields and create a related record to the user with `after_insert` after you registered the user.

If you want to explain what your aim is, I will try to suggest you a more detailed solution.

**Comment by jigarmistry** [comment]
Thanks for answer.

In my system admin can register teacher/student/parent into system. Any user can register into system as teacher/student/parent but all three having different roles into system.

i.e Teacher registration form will have class field selection but parent registration form will not have that. In the case of parent, parent only can select students and their profile information into system.

Like wise all the roles have different role into system. After the login into system teacher can not do things that parent can do.

I am going to make small erp system where all the roles have something to do.
