### ISSUE TITLE
Marketing suggestion (pages where to list weppy)

### ISSUE THREAD

**Issue by GiantCrocodile** [emmett-framework/emmett#128]
Hey @gi0baro,

a quick list of pages where we should see weppy being listed on shortly or in future for becoming more famous:
- https://www.python.org/ > section 'Use Python for…'
- https://www.python.org/about/success/#web-development
- https://www.python.org/about/apps/ > section 'Web and Internet Development'

Of course there are many more but these are important and will drive much more traffic to weppy as I believe.

Regards!

**Comment by gi0baro** [comment]
@GiantCrocodile thank you for the hints. The main question here is who should I contact to add weppy to those pages :) also, in the success story I would need someone to write an article..

**Comment by GiantCrocodile** [comment]
@gi0baro do you think that weppy should be listed there in current state or do you want to wait? If you think it is stable and feature rich enough already I will check who is responsible and get in contact with him/her to add weppy to the list.

**Comment by gi0baro** [comment]
@GiantCrocodile we'd better wait for 0.7, that should come in a couple of weeks.

**Comment by GiantCrocodile** [comment]
Short update: I've asked the webmaster team to list weppy on the mentioned pages with upcoming release of 0.7.

**Comment by gi0baro** [comment]
@GiantCrocodile Thank you very much.
