### ISSUE TITLE
New extension for Foundation 6

### ISSUE THREAD

**Issue by GiantCrocodile** [emmett-framework/emmett#133]
I suggest that we have a Foundation 6 extension next to our Bootstrap 3 extension so users have free choice.

Foundation 6: http://foundation.zurb.com/

**Comment by gi0baro** [comment]
@GiantCrocodile Yes, definitely. Maybe it's better to wait for me to complete #76, since I will update the Bootstrap3 extension too, and we won't need to patch this extension too.

**Comment by gi0baro** [comment]
Closing since too old and nobody asked for this in a long time.
