### ISSUE TITLE
Security audit for version 1.0

### ISSUE THREAD

**Issue by GiantCrocodile** [emmett-framework/emmett#166]
see title

**Comment by gi0baro** [comment]
@GiantCrocodile what do you mean?

**Comment by GiantCrocodile** [comment]
Well I mean that we need a security audit on first stable release: Version 1 is the first version which can be used in productive environment and so we need to be sure weppy has no security holes inside. Previous versions didn't fulfill this requirement as you already mention yourself in README because it is in beta:

```
Status of the project
weppy is currently released in beta stage. What does that mean?
    That the code may contain noteworthy bugs
    That you can use it on production, but cannot blame the developers if something goes wrong
```

**Comment by gi0baro** [comment]
@GiantCrocodile ok, I understand. But I meant: who and how should perform this audit? And also, how I should judge it *valid*?

**Comment by Marlysson** [comment]
@gi0baro should make how web2py , get the issues security from owasp and integrate..

**Comment by GiantCrocodile** [comment]
Sorry for my late response here. I've been busy so far. I don't know how to organize such a security audit. Maybe we have someone over here who wants to check this project in detail or there is some community who is interested in this. I just created an issue for this to make sure this isn't forgotten (at least thought about it) before releasing it. On the other hand maybe there is a nice automated tool to test for basic security principles in python source or byte code like there is for other languages and projects?

**Comment by gcmurphy** [comment]
A couple of good steps you could take is to introduce [Bandit](https://github.com/openstack/bandit) into your CI pipeline. Additionally I'd look at leveraging something like [pipenv](http://pipenv.readthedocs.io/en/latest/advanced/#detection-of-security-vulnerabilities) to check for vulnerable dependencies (or the [underlying lib it uses](https://pyup.io/safety/) to do this).
