### ISSUE TITLE
About migrations, pass argument

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#188]
Hi @gi0baro

So far I used the database with **auto_mgrate = True**
The problem (solvable) is that in the first migration creates the entire structure of the database (which already exists) and if the application obviously produces an error. What I did to fix it is to modify the method up:

```
def up(self):
     pass
```
     
Apply the migration and then re-modify the method up to its original state. And from that point it works normal forward

I checked the **new** argument, which might work, but in the first migration it generates an error:

> self._generate_migration_script(migration, source_rev.revision)
> AttributeError: 'NoneType' object has no attribute 'revision'

I thought you could include a **pass** argument that tells the migration engine not to apply the migration, but is considered as applied.

It is understood?

Maybe something similar is already implemented, but not documented

Jose

**Comment by gi0baro** [comment]
@josejachuf I'm not sure I understood the problem correctly. What's wrong with the **new** command?

**Comment by josejachuf** [comment]
@gi0baro The situation is to start using migration in an existing database. The first migration will try to create the entire database, but the database already exists and when you try to apply the migration, an error will occur. I solved it like this:
- comment all code in **up**
- apply the migration
- uncomment all the code in **up**
- From then on there will be no problems

I think having a **pass** command or whatever you want to call it, would avoid doing all of the above. Because the migration would be considered applied, even though the application does nothing.

Sorry for not being able to explain it better

**Comment by gi0baro** [comment]
@josejachuf ok now I got it.
I'll think about a specific command to just override the migration status inside the database. But I will schedule this for 1.1

**Comment by josejachuf** [comment]
Do something like this:
$ weppy --app=myapp migrations generate -m "First migration"
$ weppy --app=myapp migrations pass

> At this point we would already have synchronized the database (existing) and the migration system.

$ weppy --app=myapp migrations generate -m "Second migration"
$ weppy --app=myapp migrations up

**Comment by gi0baro** [comment]
This is implemented with https://github.com/emmett-framework/emmett/commit/ebd3f57cf6851ebf804bc2cb1b3f5bcb6b569542
