### ISSUE TITLE
Turkish Char Problem

### ISSUE THREAD

**Issue by bisguzar** [emmett-framework/emmett#224]
Hey there, firts thanks for awesome framework @gi0baro . I'm using windows nowadays and Turkish charachter is not working well on templates. I tested it on Ubuntu too, its working well on ubuntu. I think its same problem with #217 . 

I need to fix it, I have some css classes which one have Turkish charachter.

Thanks,

**Comment by gi0baro** [comment]
@bisguzar I'll need some time to test this fully on a windows environment. Will keep you updated.

**Comment by bisguzar** [comment]
I'm waiting for updates, thanks @gi0baro

**Comment by bisguzar** [comment]
Hey @gi0baro , is there any news ?

**Comment by gi0baro** [comment]
@bisguzar no I'm sorry, I didn't have time to prepare an environment on windows. I will push updates here as soon as I have any news.
