### ISSUE TITLE
Racist Motto (Framework for humans)

### ISSUE THREAD

**Issue by tweenietomatoes** [emmett-framework/emmett#230]
Hi, i noticed that your motto is kind of racist.
I was thinking what if another type of animal or alien would decide to use that framework.
It would definitely racist. So i suggest a new motto **"Framework for aliens"**, for who is residing in all galaxies and other type of unknown systems.

**Comment by gi0baro** [comment]
Since you put the topic in this way, the word "alien" is racist itself since it implies the earth is the center of everything and "aliens" are foreigners ;)

Btw, seriously the motto will change anyway in the 2.0, no worries :)

**Comment by tweenietomatoes** [comment]
I'm ashamed. Galileo rulez.
