### ISSUE TITLE
weppy still active?

### ISSUE THREAD

**Issue by GiantCrocodile** [emmett-framework/emmett#243]
Hey @gi0baro,

I'm back after some time and it was interesting to see how much weppy developed since 2016. I've checked the current developing and I'm curious if weppy is still active work in progress and thus can be used for future projects.

Best Regards from Germany!

**Comment by josejachuf** [comment]
Hi @GiantCrocodile, Please look here:
https://github.com/gi0baro/weppy/tree/next

**Comment by richarddewit** [comment]
That branch is also pretty quiet nowadays..

**Comment by gi0baro** [comment]
Hello @GiantCrocodile @richarddewit, 
as pointed out by @josejachuf the actual efforts is to complete tra async transition.

There's an open milestone for 2.0 with tasks required for a public release.
I won't lie telling you all that I expected to have more time to spend on the project, and that in the last months it was really hard for me to fulfill those steps.
On the other hand, the actual core in the `next` branch is actually used in small production services in the company I work with, and thus, even if I'm not pushing new code on that, I'm currently testing quite a lot this new async flow.

At the moment I don't have any ETAs for the new release. It would probably be quite hard to have a release before the end of the year.

Will update you guys as soon as I have news.

**Comment by GiantCrocodile** [comment]
Thanks for your reply @gi0baro! At the end, I decided against setting up a new project with weppy but it was not only because of the inactivity but also because of other open questions which delay the whole project. I appreciate a transparent communication and will keep weppy in mind!

**Comment by josejachuf** [comment]
Hi @gi0baro  have you seen vibora?

https://vibora.io/

**Comment by gi0baro** [comment]
@josejachuf yes, what about it?
At the moment I dislike the fact is not ASGI compliant.

**Comment by gi0baro** [comment]
I'm closing this, discussion can proceed in #194
