### ISSUE TITLE
From weppy to emmett

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#260]
Hi @gi0baro 

Emmet:  2.0.0a5
Emmet-REST: 1.0.0a1

I am trying to run a weppy app with the new emmett and emmett_rest. After fixing the imports the app compiles and starts the server. But for any request return an error. The app is exactly as I took it working from weppy.

> ERROR:    Application exception:
> Traceback (most recent call last):
>   File "/home/jose/emmett/venv38/lib/python3.8/site-packages/emmett/asgi/handlers.py", line 282, in dynamic_handler
>     http = await self.router.dispatch()
>   File "/home/jose/emmett/venv38/lib/python3.8/site-packages/emmett/routing/router.py", line 217, in dispatch
>     http_cls, output = await route.dispatcher.dispatch(request, reqargs)
>   File "/home/jose/emmett/venv38/lib/python3.8/site-packages/emmett/routing/dispatchers.py", line 75, in dispatch
>     await self._parallel_flow(self.flow_open)
>   File "/home/jose/emmett/venv38/lib/python3.8/site-packages/emmett/routing/dispatchers.py", line 26, in _parallel_flow
>     tasks = [asyncio.create_task(method()) for method in flow]
>   File "/home/jose/emmett/venv38/lib/python3.8/site-packages/emmett/routing/dispatchers.py", line 26, in <listcomp>
>     tasks = [asyncio.create_task(method()) for method in flow]
>   File "/usr/lib/python3.8/asyncio/tasks.py", line 382, in create_task
>     task = loop.create_task(coro)
>   File "uvloop/loop.pyx", line 1396, in uvloop.loop.Loop.create_task
> TypeError: a coroutine was expected, got None

What should I consider to do the w2e migration?

**Comment by gi0baro** [comment]
@josejachuf you also need to change all the pipeline methods inside your `Pipe`s to coroutine functions, like:

```python
class MyPipe(Pipe):
    async def open(self):
        #code 
```

**Comment by josejachuf** [comment]
Thank you. 

I advanced a little. I also had to change:

```
@capc.route("/login", methods="post")
async def login():
    url = URL_API_BASE + 'users/login'
    body_params = await request.body_params
    ...
```
I already have the login, but I still skip the same error. I was adding async and await in other places, but I don't know how to continue anymore. The problem is that the error message does not reference in which file the error is.

Best regards

**Comment by josejachuf** [comment]
@gi0baro , In this pipe is the problem. Solving this, we will see that it jumps later

```
class ApiKeyPipe(Pipe):
    def err_bad(self):
        response.status = 401
        return {'mensaje': 'No Autorizado'}

    def validate(self, auth_header):
        try:
            bearer, token = auth_header.split(' ')
        except:
            return self.err_bad()

        if (bearer != 'Bearer') or (not token) or (token == 'undefined'):
            return self.err_bad()

        try:
            token_data = jwt.decode(token, JWT_SECRET)
            current.session.uid = token_data['user_id']
        except jwt.ExpiredSignature:
            return {'mensaje': 'ExpiredSignature'}
        except jwt.InvalidAudienceError:
            return {'mensaje': 'InvalidAudienceError'}
        except jwt.DecodeError:
            return {'mensaje': 'DecodeError'}

        return None # self.err_bad()

    async def pipe(self, next_pipe, **kwargs):
        err = self.validate(request.headers.get('Authorization', ''))
        if not current.session.uid:
            response.status = 401
            return err
        return next_pipe(**kwargs)
```

**Comment by josejachuf** [comment]
my module inheritance is

```
api = app.module(__name__, 'api', url_prefix='api')
api.pipeline = [
                ServicePipe('json'),
                # CORSPipe()
                ]

v1 = api.module(__name__, 'v1', url_prefix='v1')
v1.pipeline = [
               SessionInitializer(),
               ApiKeyPipe(),
               UserFetcherPipe()
               ]
```


and then everything is inherited from v1

**Comment by josejachuf** [comment]
my module inheritance is

```
api = app.module(__name__, 'api', url_prefix='api')
api.pipeline = [
                ServicePipe('json'),
                # CORSPipe()
                ]

v1 = api.module(__name__, 'v1', url_prefix='v1')
v1.pipeline = [
               SessionInitializer(),
               ApiKeyPipe(),
               UserFetcherPipe()
               ]
```


and then everything is inherited from v1

**Comment by gi0baro** [comment]
@josejachuf you need to await `next_pipe` in `pipe` methods, eg:

```python
class MyPipe(Pipe):
    async def pipe(self, next_pipe, **kwargs):
        # code
        return await next_pipe(**kwargs)
```

**Comment by josejachuf** [comment]
Hi @gi0baro,

Except for uploads everything is working. I saw that there is a special issue about upload (not yet documented)
With weppy I have this (webservice)
```
@foo.route('/upload(/<int:pid>)?', methods=['post', 'put'])
async def upload(pid):
    """"""
    body_params = await request.body_params    
    
    if isinstance(body_params['myfile'], FieldStorage) and body_params['myfile'].filename:
        # body_params ['myfile'] does not exist. Never enters here
        ...
    else:
        ...
```

**Comment by gi0baro** [comment]
@josejachuf yes, I still writing documentation for uploads.

In Emmett you have `Request.files`, so the code would be something like this:

```python
@app.route()
async def upload():
    files = await request.files
    file = files.upload_param
    await file.save(f"somepath/{file.filename}")
```

**Comment by josejachuf** [comment]
thanks @gi0baro 

this works:

```
from emmett.wrappers.helpers import FileStorage

@foo.route('/upload(/<int:pid>)?', methods=['post', 'put'])
async def upload(pid):
    """"""
    body_params = await request.body_params
    f1 = body_params['f1']
    f2 = body_params['f2']
    files = await request.files
    f_file = files.my_file
    
    if isinstance(f_file, FileStorage) and f_file.filename:
        my_file = Mensaje.my_file.store(f_file.stream,
                                        f_file.filename
                                        )

        row = MyModel.create(f1=f1, f2=f2, my_file=my_file)
        ...
    else:
        ...
```

**Comment by gi0baro** [comment]
@josejachuf nice. Mind that the check `if isinstance(file, FileStorage)` is unnecessary, since all the contents of `request.files` are `FileStorage`.

Also mind that probably next versions will change `Model.field.store` method to make it awaitable.

**Comment by josejachuf** [comment]
> @josejachuf nice. Mind that the check `if isinstance(file, FileStorage)` is unnecessary, since all the contents of `request.files` are `FileStorage`.

OK

**Comment by gi0baro** [comment]
@josejachuf I'm gonna close this since the [upgrade guide](https://github.com/emmett-framework/emmett/blob/master/docs/upgrading.md#version-20) should be complete now.

Feel free to reopen this in case I missed any step.
