### ISSUE TITLE
'Request' object has no attribute 'environ'

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#261]
`print(dir(request))`

> ['_ScopeWrapper__parse_accept_header', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_empty_body_methods', '_input', '_input_params', '_load_params', '_load_params_form_multipart', '_load_params_form_urlencoded', '_load_params_json', '_load_params_missing', '_now', '_params_loaders', '_receive', '_scope', '_send', 'accept_language', 'body', 'body_params', 'body_timeout', 'client', 'content_length', 'content_type', 'cookies', 'files', 'headers', 'host', 'language', 'max_content_length', 'method', 'name', 'now', 'now_local', 'path', 'query_params', 'scheme']

**Comment by gi0baro** [comment]
@josejachuf yep, environ is part of WSGI specification, but not ASGI. What do you need to access?

**Comment by josejachuf** [comment]
@gi0baro I use it to access HTTP_HOST, I already saw that it is now in request.host. The documentation should be changed:
https://github.com/emmett-framework/emmett/blob/master/docs/request.md#the-request-object
