### ISSUE TITLE
RouteUrl in emmett

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#265]
Hi @gi0baro 
In weppy, in a module I use RouteUrl to sign url

`from weppy.expose import RouteUrl, url`

in emmett RouteUrl it is not. I wanted to know which module is replacing it, if there is a replacement. Will it be UrlBuilder in emmett/emmett/routing/urls.py?

this is how i am using it:

```
s = Signer(KEY)
builder = RouteUrl([url(path)])
_url = builder.url(None, None, language, args, params, None)
```

Jose

**Comment by gi0baro** [comment]
@josejachuf yep, but it's better to use `HttpUrlBuilder`, same package.
