### ISSUE TITLE
add field to model form

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#268]
Hi @gi0baro 

A weppy query, maybe the same in emmett.
I have a modelForm. I want to add a field that is not part of the model. In this particular case it is an input type checkbox. It is so that during the submit in form.accepted take some action according to the value of this extra field.
I am sure that in some project I used it, but I cannot find what I did.
Jose

**Comment by gi0baro** [comment]
@josejachuf I think the best is to actually create a standard Form that uses fields from the model and perform custom actions on acceptance.

**Comment by josejachuf** [comment]
Ok @gi0baro, I had thought of that alternative.
Thanks

**Comment by gi0baro** [comment]
@josejachuf I'm gonna close this, feel free to reopen it in case you need more help
