### ISSUE TITLE
I would like to add slug titles in Bloggy, but redirects are forced on form.params.id

### ISSUE THREAD

**Issue by vegax87** [emmett-framework/emmett#269]
I have tried to use python-slugify>=4.0.0 in order to create SEO-friendly urls in bloggy (for example `/post/<str:slug>` instead of `/post/<int:pid>` ) and I've also added `slug = slugify(title)` under Post Model, but I noticed  some issues:
1) slug doesn't appear as column in the database because it recognizes only Fields such as Field.text() and so on
2) when I replaced all pid references to slug and when I created a /new post, it forces me to redirect on form.params.id otherwise it doesn't work

**Comment by gi0baro** [comment]
@vegax87 ok, let's try to have some order:

- if you want to use the slug then you need to add the relevant column in the `Post` model
- if you want to automatically compute the slug based on another field's value, you can use [computed fields](https://emmett.sh/docs/2.0.x/orm/virtuals#computed-fields)
- if you change the field to be used to load post, you need to change the selection in the relative route

Practically speaking, update the `Post` model:

```python
from emmett.orm import compute

class Post(Model):
    slug = Field.string()

    @compute('slug')
    def compute_slug(self, row):
        return your_slug_method(row.title)
```

update the creation form:

```python
async def new_post():
    form = await Post.form()
    if form.accepted:
        redirect(url('one', Post.get(form.params.id).slug))
    return dict(form=form)
```

update the get route:

```python
@app.route("/post/<str:slug>")
async def one(slug):
    post = Post.get(slug=slug)
```

Hope is intelligible :)
