### ISSUE TITLE
Remove formatter module usage

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#273]
I'm starting to play with test on weppy in python3.6.
I get some DeprecationWarning:

> site-packages/weppy/libs/sanitizer.py:23: DeprecationWarning: the formatter module is deprecated
>     from formatter import AbstractFormatter
> 
> siste-packages/weppy/html.py:67: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
>     return cgi.escape(_to_unicode(obj), True).replace(u"'", u"&#39;")
>     
> site-packages/weppy/globals.py:102: DeprecationWarning: cgi.parse_qs is deprecated, use urllib.parse.parse_qs instead
>     dget = cgi.parse_qs(query_string, keep_blank_values=1)

**Comment by gi0baro** [comment]
@josejachuf yeah I don't think it's possible to solve them since weppy will keep Python 2.7 compatibility.

For sure the formatter should be removed from Emmett, I'll keep this open only for that.
