### ISSUE TITLE
app.render_template returns template as string

### ISSUE THREAD

**Issue by ianshk** [emmett-framework/emmett#283]
I think this is a bug, when returning app.render_template() it will not display as html but displays as a string. I think it is because no dictionary is detected.

example:
return app.render_template('error.html')

**Comment by gi0baro** [comment]
@ianshk in Emmett the default value for the `Content-Type` header is `text/plain` (in weppy was `text/html`).

You should set the proper value in the header, eg:

```python
response.content_type = "text/html"
return app.render_template("error.html")
```

Ref: https://emmett.sh/docs/2.0.x/upgrading#default-value-for-content-type-header
