### ISSUE TITLE
Possible bug with custom message validators

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#286]
Hi @gi0baro 
I think this is a possible bug.
Using validators, if for a field I create:
`'myfield': {'presence': True, message: 'my custom message'},`

this doesn't work, it always shows "Cannot be empty"
however it works fine for the other validators for example:
`{'is': 'email', message: 'my custom message'}`
or
`{'len': {'gt: 10}, message:' my custom message '}`

I'm using it on weppy 1.3.4, didn't test it on emmett

Jose

**Comment by gi0baro** [comment]
@josejachuf I confirm this is a bug in both 1.x and 2.x. Messages gets configured too early in the process: https://github.com/emmett-framework/emmett/blob/master/emmett/validators/__init__.py#L225

This will need some refactoring, probably require some time to fix.
