### ISSUE TITLE
About html.safe

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#320]
Hi @gi0baro, About [1]

in weppy **asis** is embed in templates, but now **safe** in not is embed in templates. How should it be done in these cases, I pass it with an injector? 

Jose

[1] https://emmett.sh/docs/2.2.x/upgrading#removed-sanitizer-from-libs

**Comment by gi0baro** [comment]
@josejachuf `asis` is still embed in templates also for 2.x. Unless you used `asis` with sanitizer, you won't need any changes.

**Comment by josejachuf** [comment]
Ok, Thanks @gi0baro
