### ISSUE TITLE
Request for new argument in migrations

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#366]
Hi @gi0baro,  In reference to [1] It would be good to have something like:

> emmett -a app migrations generate -m "my new table"
> emmett -a app migrations **sql**

and show the SQL script you will use 

Jose

[1] https://github.com/emmett-framework/emmett/issues/365

**Comment by josejachuf** [comment]
To see the commands that arrived at the server and understand where the error was, we activate the monitoring in the server, but not all the managers have it. Then with something like what I say help pretty. 

`emmett -a app migrations sql`
or 
`emmett -a app migrations getsql`

or something similar

**Comment by gi0baro** [comment]
@josejachuf looks like a good idea. I'm not sure I will be able to target this in 2.3, eventually will be in 2.4
