### ISSUE TITLE
Having trouble getting Emmett installed

### ISSUE THREAD

**Issue by bamarob** [emmett-framework/emmett#383]
Fresh install of MX Linux 19.4
Python 3.7.3

raldridge@mx:~$ mkdir myproject
raldridge@mx:~$ rm -rf myproject/
raldridge@mx:~$ mkdir -p myproject
raldridge@mx:~$ cd myproject/
raldridge@mx:~/myproject$ python -m venv .venv
raldridge@mx:~/myproject$ source .venv/bin/activate
(.venv) raldridge@mx:~/myproject$ pip install emmett
Collecting emmett
  Using cached https://files.pythonhosted.org/packages/ce/98/8d558e6c786f335cadb5fc0696bb151dc953da8f0e26b60630dfd434ec8b/Emmett-2.3.1-py3-none-any.whl
Collecting renoir<2.0,>=1.3 (from emmett)
  Using cached https://files.pythonhosted.org/packages/1c/af/3263234e08b3ec0ba77bacd9cf7d66212cb293536b5028a1dfdc60f7ef74/Renoir-1.4.0-py3-none-any.whl
Collecting pendulum<2.2.0,>=2.1.2 (from emmett)
  Using cached https://files.pythonhosted.org/packages/3e/40/bcf73cf69ffc4d68b80b68b5ce4e5f9d8185170e9fac65a73e247e948ff3/pendulum-2.1.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting pyyaml<6.0,>=5.4 (from emmett)
  Using cached https://files.pythonhosted.org/packages/7a/a5/393c087efdc78091afa2af9f1378762f9821c9c1d7a22c5753fb5ac5f97a/PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting h2<4.1.0,>=3.2.0 (from emmett)
  Using cached https://files.pythonhosted.org/packages/bd/c2/5ffec707d0022208787908d9657f782ce35b653baa1e87abecf22a7cf513/h2-4.0.0-py3-none-any.whl
Collecting pyDAL==17.3 (from emmett)
  Using cached https://files.pythonhosted.org/packages/e5/66/7ba446c15c4f8a24a45a23afdcd3bc21f7d113c55ad4cbded909209bb486/pyDAL-17.3-py2.py3-none-any.whl
Collecting h11<0.11.0,>=0.10.0 (from emmett)
  Using cached https://files.pythonhosted.org/packages/1f/0d/9a3a4de68d76bbacd4851ed9be9aeef8f170532d3907e009fe1fda81d350/h11-0.10.0-py2.py3-none-any.whl
Collecting pyaes<1.7.0,>=1.6.1 (from emmett)
  Using cached https://files.pythonhosted.org/packages/44/66/2c17bae31c906613795711fc78045c285048168919ace2220daa372c7d72/pyaes-1.6.1.tar.gz
Collecting uvicorn==0.14.0 (from emmett)
  Using cached https://files.pythonhosted.org/packages/bf/fe/a41994c92897b162c0c83e8ef10bec54ebdefbce3f3725b530d2091492ac/uvicorn-0.14.0-py3-none-any.whl
Collecting websockets<10.0,>=9.1 (from emmett)
  Using cached https://files.pythonhosted.org/packages/3b/bd/6f63619fecddef9c411e0390274194f46f7596ae69945c1fd0a1f8caaf4a/websockets-9.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting severus<2.0,>=1.1 (from emmett)
  Using cached https://files.pythonhosted.org/packages/ff/15/458f2f7fe45bd4586c5543df08b1f02d0e6e07a48d43b2a2efe7503f107c/Severus-1.1.1-py3-none-any.whl
Collecting python-rapidjson<2.0,>=1.0 (from emmett)
  Using cached https://files.pythonhosted.org/packages/e7/3a/2aeaac70249ba1c928a8633b85898219fbad20987d42f81185b2fac90a73/python_rapidjson-1.4-cp37-cp37m-manylinux1_x86_64.whl
Collecting click>=6.0 (from emmett)
  Using cached https://files.pythonhosted.org/packages/76/0a/b6c5f311e32aeb3b406e03c079ade51e905ea630fc19d1262a46249c1c86/click-8.0.1-py3-none-any.whl
Collecting httptools<0.3.0,>=0.2.0; sys_platform != "win32" (from emmett)
  Using cached https://files.pythonhosted.org/packages/4c/87/ebb92639705924aac5ed6aa91bd4332b20d7180f3e94bd168742e7671025/httptools-0.2.0-cp37-cp37m-manylinux1_x86_64.whl
Collecting uvloop<0.16.0,>=0.15.3; sys_platform != "win32" (from emmett)
  Using cached https://files.pythonhosted.org/packages/41/49/d2cdac6450430f444d3df59ccd1abc8225ea51ffcecd9ac2e36b111074a4/uvloop-0.15.3.tar.gz
Collecting python-dateutil<3.0,>=2.6 (from pendulum<2.2.0,>=2.1.2->emmett)
  Using cached https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl
Collecting pytzdata>=2020.1 (from pendulum<2.2.0,>=2.1.2->emmett)
  Using cached https://files.pythonhosted.org/packages/e0/4f/4474bda990ee740a020cbc3eb271925ef7daa7c8444240d34ff62c8442a3/pytzdata-2020.1-py2.py3-none-any.whl
Collecting hpack<5,>=4.0 (from h2<4.1.0,>=3.2.0->emmett)
  Using cached https://files.pythonhosted.org/packages/d5/34/e8b383f35b77c402d28563d2b8f83159319b509bc5f760b15d60b0abf165/hpack-4.0.0-py3-none-any.whl
Collecting hyperframe<7,>=6.0 (from h2<4.1.0,>=3.2.0->emmett)
  Using cached https://files.pythonhosted.org/packages/d7/de/85a784bcc4a3779d1753a7ec2dee5de90e18c7bcf402e71b51fcf150b129/hyperframe-6.0.1-py3-none-any.whl
Collecting typing-extensions; python_version < "3.8" (from uvicorn==0.14.0->emmett)
  Using cached https://files.pythonhosted.org/packages/74/60/18783336cc7fcdd95dae91d73477830aa53f5d3181ae4fe20491d7fc3199/typing_extensions-3.10.0.2-py3-none-any.whl
Collecting asgiref>=3.3.4 (from uvicorn==0.14.0->emmett)
  Using cached https://files.pythonhosted.org/packages/fe/66/577f32b54c50dcd8dec38447258e82ed327ecb86820d67ae7b3dea784f13/asgiref-3.4.1-py3-none-any.whl
Collecting importlib-metadata; python_version < "3.8" (from click>=6.0->emmett)
  Using cached https://files.pythonhosted.org/packages/71/c2/cb1855f0b2a0ae9ccc9b69f150a7aebd4a8d815bd951e74621c4154c52a8/importlib_metadata-4.8.1-py3-none-any.whl
Collecting six>=1.5 (from python-dateutil<3.0,>=2.6->pendulum<2.2.0,>=2.1.2->emmett)
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->click>=6.0->emmett)
  Using cached https://files.pythonhosted.org/packages/92/d9/89f433969fb8dc5b9cbdd4b4deb587720ec1aeb59a020cf15002b9593eef/zipp-3.5.0-py3-none-any.whl
Building wheels for collected packages: pyaes, uvloop
  Running setup.py bdist_wheel for pyaes ... error
  Complete output from command /home/raldridge/myproject/.venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vob3v956/pyaes/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-h144yk0f --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pyaes
  Running setup.py clean for pyaes
  Running setup.py bdist_wheel for uvloop ... error
  Complete output from command /home/raldridge/myproject/.venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vob3v956/uvloop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-qaq36_6j --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for uvloop
  Running setup.py clean for uvloop
Failed to build pyaes uvloop
Installing collected packages: renoir, six, python-dateutil, pytzdata, pendulum, pyyaml, hpack, hyperframe, h2, pyDAL, h11, pyaes, typing-extensions, zipp, importlib-metadata, click, asgiref, uvicorn, websockets, severus, python-rapidjson, httptools, uvloop, emmett
  Running setup.py install for pyaes ... done
  Running setup.py install for uvloop ... error
    Complete output from command /home/raldridge/myproject/.venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vob3v956/uvloop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-5k8met93/install-record.txt --single-version-externally-managed --compile --install-headers /home/raldridge/myproject/.venv/include/site/python3.7/uvloop:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/_version.py -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/_noop.py -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/__init__.py -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/_testbase.py -> build/lib.linux-x86_64-3.7/uvloop
    running egg_info
    writing uvloop.egg-info/PKG-INFO
    writing dependency_links to uvloop.egg-info/dependency_links.txt
    writing requirements to uvloop.egg-info/requires.txt
    writing top-level names to uvloop.egg-info/top_level.txt
    reading manifest file 'uvloop.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/.git'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/docs'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/img'
    writing manifest file 'uvloop.egg-info/SOURCES.txt'
    copying uvloop/cbhandles.pxd -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/cbhandles.pyx -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/dns.pyx -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/errors.pyx -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/loop.c -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/loop.pxd -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/loop.pyi -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/loop.pyx -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/lru.pyx -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/pseudosock.pyx -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/py.typed -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/request.pxd -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/request.pyx -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/server.pxd -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/server.pyx -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/sslproto.pxd -> build/lib.linux-x86_64-3.7/uvloop
    copying uvloop/sslproto.pyx -> build/lib.linux-x86_64-3.7/uvloop
    creating build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/async_.pxd -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/async_.pyx -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/basetransport.pxd -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/basetransport.pyx -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/check.pxd -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/check.pyx -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/handle.pxd -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/handle.pyx -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/idle.pxd -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/idle.pyx -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/pipe.pxd -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/pipe.pyx -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/poll.pxd -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/poll.pyx -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/process.pxd -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/process.pyx -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/stream.pxd -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/stream.pyx -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/streamserver.pxd -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/streamserver.pyx -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/tcp.pxd -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/tcp.pyx -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/timer.pxd -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/timer.pyx -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/udp.pxd -> build/lib.linux-x86_64-3.7/uvloop/handles
    copying uvloop/handles/udp.pyx -> build/lib.linux-x86_64-3.7/uvloop/handles
    creating build/lib.linux-x86_64-3.7/uvloop/includes
    copying uvloop/includes/__init__.py -> build/lib.linux-x86_64-3.7/uvloop/includes
    copying uvloop/includes/compat.h -> build/lib.linux-x86_64-3.7/uvloop/includes
    copying uvloop/includes/consts.pxi -> build/lib.linux-x86_64-3.7/uvloop/includes
    copying uvloop/includes/debug.h -> build/lib.linux-x86_64-3.7/uvloop/includes
    copying uvloop/includes/debug.pxd -> build/lib.linux-x86_64-3.7/uvloop/includes
    copying uvloop/includes/flowcontrol.pxd -> build/lib.linux-x86_64-3.7/uvloop/includes
    copying uvloop/includes/fork_handler.h -> build/lib.linux-x86_64-3.7/uvloop/includes
    copying uvloop/includes/python.pxd -> build/lib.linux-x86_64-3.7/uvloop/includes
    copying uvloop/includes/stdlib.pxi -> build/lib.linux-x86_64-3.7/uvloop/includes
    copying uvloop/includes/system.pxd -> build/lib.linux-x86_64-3.7/uvloop/includes
    copying uvloop/includes/uv.pxd -> build/lib.linux-x86_64-3.7/uvloop/includes
    running build_ext
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking whether make supports the include directive... yes (GNU style)
    checking dependency style of gcc... gcc3
    checking for gcc way to treat warnings as errors... -Werror
    checking if gcc supports -fvisibility=hidden... yes
    checking if gcc supports -g flag... yes
    checking if gcc supports -std=gnu89 flag... yes
    checking if gcc supports -Wall flag... yes
    checking if gcc supports -Wextra flag... yes
    checking if gcc supports -Wno-long-long flag... yes
    checking if gcc supports -Wno-unused-parameter flag... yes
    checking if gcc supports -Wstrict-prototypes flag... yes
    checking for ar... ar
    checking the archiver (ar) interface... ar
    checking how to print strings... printf
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /usr/bin/dd
    checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking whether make supports nested variables... (cached) yes
    checking whether gcc is Clang... no
    checking whether pthreads work with -pthread... yes
    checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
    checking whether more special flags are required for pthreads... no
    checking for PTHREAD_PRIO_INHERIT... yes
    checking for dlopen in -ldl... yes
    checking for library containing kstat_lookup... no
    checking for library containing gethostbyname... none required
    checking for library containing perfstat_cpu... no
    checking for library containing clock_gettime... none required
    checking for library containing sendfile... none required
    checking for library containing socket... none required
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking sys/ahafs_evProds.h usability... no
    checking sys/ahafs_evProds.h presence... no
    checking for sys/ahafs_evProds.h... no
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating libuv.pc
    config.status: executing depfiles commands
    config.status: executing libtool commands
      CC       src/libuv_la-fs-poll.lo
      CC       src/libuv_la-idna.lo
      CC       src/libuv_la-inet.lo
      CC       src/libuv_la-random.lo
      CC       src/libuv_la-strscpy.lo
      CC       src/libuv_la-threadpool.lo
      CC       src/libuv_la-timer.lo
      CC       src/libuv_la-uv-data-getter-setters.lo
      CC       src/libuv_la-uv-common.lo
      CC       src/libuv_la-version.lo
      CC       src/unix/libuv_la-async.lo
      CC       src/unix/libuv_la-core.lo
      CC       src/unix/libuv_la-dl.lo
      CC       src/unix/libuv_la-fs.lo
      CC       src/unix/libuv_la-getaddrinfo.lo
      CC       src/unix/libuv_la-getnameinfo.lo
      CC       src/unix/libuv_la-loop-watcher.lo
      CC       src/unix/libuv_la-loop.lo
      CC       src/unix/libuv_la-pipe.lo
      CC       src/unix/libuv_la-poll.lo
      CC       src/unix/libuv_la-process.lo
      CC       src/unix/libuv_la-random-devurandom.lo
      CC       src/unix/libuv_la-signal.lo
      CC       src/unix/libuv_la-stream.lo
      CC       src/unix/libuv_la-tcp.lo
      CC       src/unix/libuv_la-thread.lo
      CC       src/unix/libuv_la-tty.lo
      CC       src/unix/libuv_la-udp.lo
      CC       src/unix/libuv_la-linux-core.lo
      CC       src/unix/libuv_la-linux-inotify.lo
      CC       src/unix/libuv_la-linux-syscalls.lo
      CC       src/unix/libuv_la-procfs-exepath.lo
      CC       src/unix/libuv_la-proctitle.lo
      CC       src/unix/libuv_la-random-getrandom.lo
      CC       src/unix/libuv_la-random-sysctl-linux.lo
      CCLD     libuv.la
    building 'uvloop.loop' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/uvloop
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/raldridge/myproject/.venv/include -I/usr/include/python3.7m -I/tmp/pip-install-vob3v956/uvloop/vendor/libuv/include -c uvloop/loop.c -o build/temp.linux-x86_64-3.7/uvloop/loop.o -O2
    uvloop/loop.c:22:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/raldridge/myproject/.venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vob3v956/uvloop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-5k8met93/install-record.txt --single-version-externally-managed --compile --install-headers /home/raldridge/myproject/.venv/include/site/python3.7/uvloop" failed with error code 1 in /tmp/pip-install-vob3v956/uvloop/
(.venv) raldridge@mx:~/myproject$

**Comment by gi0baro** [comment]
I would suggest you to issue a:

    pip install -U pip

after the `source .venv/bin/activate` and before installing emmet. This _should_ fix most of your issues.

**Comment by bamarob** [comment]
Excellent! That worked perfectly!  Thank you!
