### ISSUE TITLE
Support MariaDB Connector 

### ISSUE THREAD

**Issue by tweenietomatoes** [emmett-framework/emmett#440]
Currently we can't use MariaDB connector with emmett orm. Is it possible to add mariadb support?

**Comment by gi0baro** [comment]
@tweenietomatoes you should be able to use the mysql driver and adapter with MariaDB

**Comment by tweenietomatoes** [comment]
Well i am trying this:
`results = Data.all().select(paginate=1)`

However i get all result instead of single result.

**Comment by gi0baro** [comment]
@tweenietomatoes as [explained in the documentation](https://emmett.sh/docs/2.4.x/orm/operations#pagination), `paginate=1` will simply return the first page, if you want a single record you should use `paginate=(1,1)` or `limitby=(0,1)`.

Also, selection always returns a `Rows` object, you may want to use the `.first()` method in case you want a single record.
