### ISSUE TITLE
Copy or clone row

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#477]
Please add a new feature to the ORM that allows you to create a record from an existing one. See [1]

I had thought about something similar to how you can create a structure from another in Rust

```
class MyModel(Model):
    a = Field()
    a = Field()
    c= Field.int()

foo = MyModel.get(id=1)

bar = MyModel.copy(foo) # Copy a, b and c

bar_2 = MyModel.copy(a='emmett', foo) # Copy b and c, but not a
bar_2 = MyModel.copy(foo, a='emmett') # Copy b and c, but not a

```

Thanks

[1] https://github.com/emmett-framework/emmett/discussions/393

**Comment by gi0baro** [comment]
@josejachuf I was circling back on open issues and just noticed that actually both `Row` and `StructuredRow` in ORM objects implement `__copy__`, so this should work:

```python
import copy

foo = MyModel.get(1)
bar = copy.copy(foo)
foo.a = "emmett"
foo.save()
```

Is this enough for your case, or you need also `__deepcopy__`?

**Comment by josejachuf** [comment]
I'll see. Thank you so much!
