### ISSUE TITLE
Use models in multiple databases 

### ISSUE THREAD

**Issue by erhuabushuo** [emmett-framework/emmett#485]
In a database master-slave ,  I need define same models with two databases. How can I specify which connection when I query by using Model

**Comment by gi0baro** [comment]
The only existing support you have for this today is defining a subclass for every database instance you want to support, eg:

```python
from emmett.orm import Model, Field

class MyModel(Model):
    tablename = "mymodel"
    foo = Field()

class MyReadModel(MyModel):
    ...

class MyWriteModel(MyModel):
    ...

dbr.define_models(MyReadModel)
dbw.define_models(MyWriteModel)
```

**Comment by erhuabushuo** [comment]
Thanks a lot.
