### ISSUE TITLE
Add docs for emmett.helpers

### ISSUE THREAD

**Issue by pramos84** [emmett-framework/emmett#493]
Hi, guys. Just to remember to create docs for the emmett.helpers. "abort" and "flash" are presented in some examples through the docs, but "stream_file" is not mentioned, despite to be a very useful method. Thanks.

**Comment by gaytomycode** [comment]
@pramos84 thank you for pointing this out. Would appreciate your further assistance by checking my PR and telling me any feedback you have 🙏

**Comment by pramos84** [comment]
Very good, @gaytomycode. Thank you. I suggest to add some reference to this helpers on "Handling requests" or "Building responses" sections. "Building responses" would be the most apropriate, in my opinion. I started my search there, before to open the discussion. Thanks again.

**Comment by gaytomycode** [comment]
@pramos84 that makes sense. Thank you for your feedback will modify the PR.

**Comment by gi0baro** [comment]
Closing this as in 2.6 stream helpers will be deprecated.
