### ISSUE TITLE
Using HTTPIO with zipfile?

### ISSUE THREAD

**Issue by mayli** [emmett-framework/emmett#504]
So, I am trying to serve files directly from a zipfile, 
```
@app.route("/web/<any:path>")
async def web(path="index.html"):
   return HTTPIO(zip.open(path))
```
However I only get `<zipfile.ZipExtFile name='index.html' mode='r' compress_type=deflate>` in response, did I miss something?

**Comment by gi0baro** [comment]
It might be a bit counter-intuitive, but `HTTP` classes are actually exceptions, so when you use them directly in routes you need to `raise`.

**Comment by mayli** [comment]
Ahh, yeah, i think that could be documented for people returning non-text responses.

**Comment by gi0baro** [comment]
> Ahh, yeah, i think that could be documented for people returning non-text responses.

2.6 (coming in the next weeks) will have new facilities for non-text responses.
