### ISSUE TITLE
error with upload field [emmett 2.6]

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#520]
I have this model. When "archivo" of the upload type is optional. When I attach it, it works fine, when it is not attached, it gives error:

```python
class InformeReparticion(Signature):
    tablename = "informes_reparticiones"
    belongs_to({'tramite': 'Tramite'})
    belongs_to({'reparticion': 'Reparticion'})
    fecha = Field.date()
    aprobado = Field.bool()
    observaciones = Field.text()
    archivo = Field.upload()
```

> 
> [ERROR] Application callable raised an exception
> Traceback (most recent call last):
>   File "/venv/lib/python3.12/site-packages/granian/_futures.py", line 4,
>  in future_watcher
>     await inner(watcher.scope, watcher.proto)
>   File "/venv/lib/python3.12/site-packages/granian/rsgi.py", line 81, in
>  _http_logger
>     rv = await callback(scope, proto)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/venv/lib/python3.12/site-packages/emmett_core/protocols/rsgi/ha
> ndlers.py", line 63, in __call__
>     if coro := http.rsgi(protocol):
>                ^^^^^^^^^^^^^^^^^^^
>   File "/venv/lib/python3.12/site-packages/emmett_core/http/response.py"
> , line 69, in rsgi
>     protocol.response_bytes(self.status_code, list(self.rsgi_headers), self.body)
>   File "/venv/lib/python3.12/site-packages/granian/rsgi.py", line 66, in
>  response_bytes
>     return self.inner.response_bytes(status, headers, body)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: argument 'body': 'str' object cannot be converted to 'PyByteArray'

**Comment by gi0baro** [comment]
@josejachuf can you provide more context to this? which request produces that error? Is the form get/post, the download, or something else?

**Comment by gi0baro** [comment]
@josejachuf can you confirm you're on the latest `emmett-core` version (1.0.3)?

**Comment by josejachuf** [comment]
Yes, I use emmett-core 1.0.3


> emmett             2.6.1
> emmett-core        1.0.3
> emmett-crypto      0.6.0
> emmett-pydal       17.3.1
> emmett-rest        1.6.0
> renoir             1.8.0
> granian            1.6.3

**Comment by josejachuf** [comment]
![imagen](https://github.com/user-attachments/assets/7469d0d5-27ba-4f90-a9b2-a91cadf9a664)

after submit

![imagen](https://github.com/user-attachments/assets/5e8302d7-8638-4630-ba44-7b88d33f3301)

**Comment by josejachuf** [comment]
Sorry @gi0baro , the first message:

> [ERROR] Application callable raised an exception
> Traceback (most recent call last):
> File "/venv/lib/python3.12/site-packages/granian/_futures.py", line 4,
> in future_watcher
> await inner(watcher.scope, watcher.proto)
> File "/venv/lib/python3.12/site-packages/granian/rsgi.py", line 81, in
> _http_logger
> rv = await callback(scope, proto)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/venv/lib/python3.12/site-packages/emmett_core/protocols/rsgi/ha
> ndlers.py", line 63, in call
> if coro := http.rsgi(protocol):
> ^^^^^^^^^^^^^^^^^^^
> File "/venv/lib/python3.12/site-packages/emmett_core/http/response.py"
> , line 69, in rsgi
> protocol.response_bytes(self.status_code, list(self.rsgi_headers), self.body)
> File "/venv/lib/python3.12/site-packages/granian/rsgi.py", line 66, in
> response_bytes
> return self.inner.response_bytes(status, headers, body)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: argument 'body': 'str' object cannot be converted to 'PyByteArray'


corresponds to  emmett-core 1.0.2 and the second error: **Invalid multipart data** corresponds to emmett-core 1.0.3
