### ISSUE TITLE
'Emmett develop' produce the following

### ISSUE THREAD

**Issue by ockan** [emmett-framework/emmett#532]
2.6.2,'Emmett develop' produce the following
![截屏2024-12-24 08 42 11](https://github.com/user-attachments/assets/694ebc68-18ca-447a-9696-d4ce8302b22d)

**Comment by Charlton-A** [comment]
Had the same issue when using granian>=1.7.0 . Add granian==1.6.4 to your requirements.

**Comment by gi0baro** [comment]
This is fixed in the upcoming Granian 1.7.2
