### ISSUE TITLE
the dependency package 'pendulum' can be removed if optimize

### ISSUE THREAD

**Issue by ockan** [emmett-framework/emmett#534]
if remove the dependency package 'pendulum',the venv environment will minus 5 dependency packages.
in fact, only 9 .py files need it, if optimize, the dependency package 'pendulum' can be removed.
![截屏2024-12-28 16 08 32](https://github.com/user-attachments/assets/0d36e11e-7455-41e5-a9cb-def3a8830900)

**Comment by gi0baro** [comment]
I don't really get the whole "too many deps" _extremism_, but in general every dependency in Emmett is there for its functionalities and features, not just because I wanted everyone to have bigger venvs out there.

**Comment by ockan** [comment]
yes, almost no one cares how many deps what a framework use, but for the framework developers, too many dependency packeges to be maintance its version upgrading are exhausting energy of himself.

emmett just use pendulum's datetime type and its functions, that's sole. but if import pendulum, also import 5 packeges what pendulum depends. they are:
python-dateutil, tzdata, time-machine, six and pendulum itself.
