### ISSUE TITLE
Generate client-side javascript form validation equal to server validation

### ISSUE THREAD

**Issue by GiantCrocodile** [emmett-framework/emmett#63]
I think it would be useful if you have javascript based client-side validation too which checks for the same as your server validation and is generated automatically. This prevent users from submitting data before it is complete or correct: better usability and tiny less server load.

**Comment by CompadreP** [comment]
Yes, that's what I'm missing in Django. This could be really great.

**Comment by GiantCrocodile** [comment]
This should be optional and could be a good extension :).

**Comment by gi0baro** [comment]
Closing this since too old and probably handled by #255
