### ISSUE TITLE
Automatic changelog generation for weppy

### ISSUE THREAD

**Issue by GiantCrocodile** [emmett-framework/emmett#68]
Maybe this could reduce your (at the moment low but higher in future) management workload: https://github.com/skywinder/github-changelog-generator

It will generate changelogs automatically with help of your issue and commit list.

**Comment by mijdavis2** [comment]
:+1: I use github-changelog-generator wherever I can, including the weppy-mvc generator.

The only issue is that it requires strict use of issues and pull requests to actually log changes. It seems if branches are merged without being tagged with issues or without a PR, it neglects them entirely.
